# Generated by Django 5.0.6 on 2024-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_account_app_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='headers',
            field=models.JSONField(null=True),
        ),
    ]
